### ISSUE TITLE
deliteful/tests/functional/StartRating.js test has been failing

### ISSUE THREAD

**Issue by edchat** [ibm-js/deliteful#465]
It has been failing since this change in delite: https://github.com/ibm-js/delite/commit/00f0b74736e4b1a9473ef0c1a1d8ed5971f15bcd
The problem is related to having the `<input>` defined inside the d-star-rating tag, like this:
```javascript
Default: <d-star-rating id="starratingA" max=7 value="1"><input name="star1"></d-star-rating>
```
You can see the problem by hitting http://<myPath>/deliteful/tests/functional/StarRating-formback.html and clicking submit.  It should return the Name/value pairs, but it is not getting the name, and it is getting undefined for the value.  

If the name is also set on the d-star-rating node it will work, but when it was working before prior to https://github.com/ibm-js/delite/commit/00f0b74736e4b1a9473ef0c1a1d8ed5971f15bcd the name was not being set on the d-star-rating node.

We could set the name into the d-star-rating node in createdCallback in StarRating.js where is sets up the input, but I am not sure why that is needed now when it was not needed before.
@wkeese any thoughts?

**Comment by wkeese** [comment]
Looks like a bug in StarRating itself.   For some reason StarRating calls `notifyCurrentValue()` on `name`:

```js
this.notifyCurrentValue("disabled", "max", "value", "name", "readOnly", "allowZero");
```

That means that even when the user hasn't specified `name` on the StarRating widget itself, StarRating will copy `name`'s default value (i.e. "") to the `<input>`, overwriting what was specified in the original markup.

BTW, IIUC we are supposed to be supporting two API's:

1) No back/forward button support

```js
// create a StarRating widget, but the back/forward buttons won't save the value
new StarRating({name: "foo"})
```

or in markup:

```html
<d-star-rating name=foo></d-star-rating>
```

2) Back/forward support

```html
<d-star-rating><input name=foo></d-star-rating>
```

I wish we could drop (2), and get back/forward working in case (1) (at least the markup version), but I tried it and the back/forward buttons don't seem to work unless the `<input>` has name initially specified.


PS: This code in StarRating.js is now presumably unnecessary:

```js
if ("name" in props && this.name) {
	this.valueNode.name = this.name;
}
```

**Comment by edchat** [comment]
Fixed by https://github.com/ibm-js/deliteful/commit/426c460015d7aeb8395b869f1012df612ce378e2

**Comment by cjolif** [comment]
According to travis the tests are still failing: https://travis-ci.org/ibm-js/deliteful/builds/48101214 ? But maybe this was just a temporary failure?

**Comment by cjolif** [comment]
subsequent builds also highlight the error so this is probably not just temporary.

**Comment by edchat** [comment]
So the tests pass for me when running with delite master.  Currently deliteful has "delite": "0.6.x", in bower.json.  And delite has "version": "0.6.0-alpha.3", in package.json.  It seems like travis should be picking up the latest delite correct?

**Comment by cjolif** [comment]
I guess the fix you need is between 0.6.0-alpha3 and master... @wkeese will have to tag a new one.

**Comment by edchat** [comment]
With this commit from wkeese https://github.com/ibm-js/delite/commit/2ee37b64eaca8dc31f2438fd85a0326ab03438b9 the StarRating tests are now passing.
