### ISSUE TITLE
ViewStack: showNext & showPrevious do not have any jsdoc

### ISSUE THREAD

**Issue by cjolif** [ibm-js/deliteful#468]
Also it seems the jsdoc of the show() method is not correctly following the guidelines for the parameters (see DisplayContainer which is doing differently).

**Comment by dmandrioli** [comment]
Fixed in https://github.com/ibm-js/deliteful/commit/827907b229e13c010c838f18d8e8537c4dcc3fb6

**Comment by cjolif** [comment]
You did not fix
`Also it seems the jsdoc of the show() method is not correctly following the guidelines for the parameters `

**Comment by cjolif** [comment]
This is basically the same comment as @wkeese here: https://github.com/ibm-js/deliteful/commit/827907b229e13c010c838f18d8e8537c4dcc3fb6#commitcomment-9458113 but on existing show method.

**Comment by cjolif** [comment]
ok was done in a subsequent commit.
